apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ode
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jrichter/oda:bb00b8899fc18d45c93f9bc40812aeea33924700@sha256:87c1a53dab3f673140b5d13a403e6f6b72421e12c8ee9fdd5416e3e3ed83cf83 # use pre-built to bootstrap 
          name: app-inference
